version: 2.1
orbs:
  docker: circleci/docker@2.2.0
  snyk: snyk/snyk@1.7.0
  
jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run: mvn clean package
      - run: |
          echo "Running tests..."
          mvn test

  snyk_scan:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run: mvn clean package
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
        docker-image-name: $IMAGE_NAME

  docker_build_and_push:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run: mvn clean package
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
            docker build -t ${DOCKER_LOGIN}/harbour-booking-api:${CIRCLE_SHA1} .
            docker push ${DOCKER_LOGIN}/harbour-booking-api:${CIRCLE_SHA1}

workflows:
  version: 2
  ci_flow:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: develop
      - snyk_scan:
          requires:
            - build_and_test
          filters:
            branches:
              only: develop

  ci_cd_flow:
    jobs:
      - docker_build_and_push:
          filters:
            branches:
              only: release
