version: 2.1
orbs:
  docker:circleci/docker@2.2.0
  snyk: snyk/snyk@1.70

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      # Fetch source code from repo
      - checkout

      # Package into a jar
      - run: mvn clean package
     - run: |
          echo “Running tests...”
          mvn test
#Job to perform snyk scan
snyk_scan:
  docker:
  - image: cimg/openjdk:17.0.7
  enviroment:
    IMAGE_NAME: afifrifaie/habour-booking-api
    steps:
    - checkout
    - run: mvn clean package
    - setup_remote_docker
    - docker/check
    - run: docker build -t $IMAGE_NAME .
    - snyk/scan:
      docker-image-name: $IMAGE_NAME

#Job to build Docker image and push to DockerHub
  docker_build_and_deploy:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      # Fetch source code from repo
      - checkout

      # Package into a jar
      - run: mvn clean package


      # configure CircleCI to use Docker
      - setup_remote_docker

      - run:
          name: Build and Push Docker Image
          # Build docker image and tag it with commit SHA, then push to docker hub
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker build -t ${DOCKER_USER}/harbour-booking-api:${CIRCLE_SHA1} . \
            && docker build -t ${DOCKER_USER}/harbour-booking-api:latest . \
            && docker push ${DOCKER_USER}/harbour-booking-api:${CIRCLE_SHA1} \
            && docker push ${DOCKER_USER}/harbour-booking-api:latest

            workflows:
  version: 2
  ci_flow:
    jobs:
      # Define jobs to be executed for CI (develop branch)
      - build_and_test:
          filters:
            branches:
              only:
                - develop
      - snyk_scan:
        requires:
        - build_and_test
        filters:
          branches:
            only: develop
      # Define jobs to be executed for CI/CD (release branch)
      cicd_flow:
      jobs:
      - docker_build_and_deploy:
          filters:
            branches:
              only:
                - release
