version: 2.1
orbs:
  docker: circleci/docker@2.2.0
  snyk: snyk/snyk@1.70

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      # Fetch source code from repo
      - checkout

      # Package into a jar
      - run: mvn clean package

      # Run tests
      - run: |
          echo "Running tests..."
          mvn test

workflows:
  version: 2
  ci_cd_workflow:
    jobs:
      # Define jobs to be executed for CI (develop branch)
      - build:
          filters:
            branches:
              only:
                - develop

      # Define jobs to be executed for CI/CD (release branch)
      - snyk_scan:
          requires:
            - build
          filters:
            branches:
              only:
                - develop

      - docker_build_and_deploy:
          requires:
            - snyk_scan
          filters:
            branches:
              only:
                - release
